//Types
export const types = {
    SET_MOVIES: 'SET_MOVIES',
    SET_MOVIE_ITEM: 'SET_MOVIE_ITEM',
    SHOW_MOVIE_ITEM: 'SHOW_MOVIE_ITEM',
    HIDE_MOVIE_ITEM: 'HIDE_MOVIE_ITEM',
    DELETE_MOVIE_ITEM: 'DELETE_MOVIE_ITEM',
    DOWNLOAD_MOVIES_FILE: 'DOWNLOAD_MOVIES_FILE',
}
