export const movies = [
    {
        title: 'Blazing Saddles',
        release: 1974,
        format: 'VHS',
        stars: 'Mel Brooks, Clevon Little, Harvey Korman, Gene Wilder, Slim Pickens, Madeline Kahn',
    },
    {
        title: 'Casablanca',
        release: 1942,
        format: 'DVD',
        stars: 'Humphrey Bogart, Ingrid Bergman, Claude Rains, Peter Lorre',
    },
    {
        title: 'Charade',
        release: 1953,
        format: 'DVD',
        stars: 'Audrey Hepburn, Cary Grant, Walter Matthau, James Coburn, George Kennedy',
    },
    {
        title: 'Cool Hand Luke',
        release: 1967,
        format: 'VHS',
        stars: 'Paul Newman, George Kennedy, Strother Martin',
    },
    {
        title: 'Butch Cassidy and the Sundance Kid',
        release: 1969,
        format: 'VHS',
        stars: 'Paul Newman, Robert Redford, Katherine Ross',
    },
    {
        title: 'The Sting',
        release: 1973,
        format: 'DVD',
        stars: 'Robert Redford, Paul Newman, Robert Shaw, Charles Durning',
    },
    {
        title: 'The Muppet Movie',
        release: 1979,
        format: 'DVD',
        stars: 'Jim Henson, Frank Oz, Dave Geolz, Mel Brooks, James Coburn, Charles Durning, Austin Pendleton',
    },
    {
        title: 'Get Shorty',
        release: 1995,
        format: 'DVD',
        stars: 'John Travolta, Danny DeVito, Renne Russo, Gene Hackman, Dennis Farina',
    },
    {
        title: 'My Cousin Vinny',
        release: 1992,
        format: 'DVD',
        stars: 'Joe Pesci, Marrisa Tomei, Fred Gwynne, Austin Pendleton, Lane Smith, Ralph Macchio',
    },
    {
        title: 'Gladiator',
        release: 2000,
        format: 'Blu-Ray',
        stars: 'Russell Crowe, Joaquin Phoenix, Connie Nielson',
    },
    {
        title: 'Star Wars',
        release: 1977,
        format: 'Blu-Ray',
        stars: 'Harrison Ford, Mark Hamill, Carrie Fisher, Alec Guinness, James Earl Jones',
    },
    {
        title: 'Raiders of the Lost Ark',
        release: 1981,
        format: 'DVD',
        stars: 'Harrison Ford, Karen Allen',
    },
    {
        title: 'Serenity',
        release: 2005,
        format: 'Blu-Ray',
        stars: 'Nathan Fillion, Alan Tudyk, Adam Baldwin, Ron Glass, Jewel Staite, Gina Torres, Morena Baccarin, Sean Maher, Summer Glau, Chiwetel Ejiofor',
    },
    {
        title: 'Hooisers',
        release: 1986,
        format: 'VHS',
        stars: 'Gene Hackman, Barbara Hershey, Dennis Hopper',
    },
    {
        title: 'WarGames',
        release: 1983,
        format: 'VHS',
        stars: 'Matthew Broderick, Ally Sheedy, Dabney Coleman, John Wood, Barry Corbin',
    },
    {
        title: 'Spaceballs',
        release: 1987,
        format: 'DVD',
        stars: 'Bill Pullman, John Candy, Mel Brooks, Rick Moranis, Daphne Zuniga, Joan Rivers',
    },
    {
        title: 'Young Frankenstein',
        release: 1974,
        format: 'VHS',
        stars: 'Gene Wilder, Kenneth Mars, Terri Garr, Gene Hackman, Peter Boyle',
    },
    {
        title: 'Real Genius',
        release: 1985,
        format: 'VHS',
        stars: 'Val Kilmer, Gabe Jarret, Michelle Meyrink, William Atherton',
    },
    {
        title: 'Top Gun',
        release: 1986,
        format: 'DVD',
        stars: 'Tom Cruise, Kelly McGillis, Val Kilmer, Anthony Edwards, Tom Skerritt',
    },
    {
        title: 'MASH',
        release: 1970,
        format: 'DVD',
        stars: 'Donald Sutherland, Elliot Gould, Tom Skerritt, Sally Kellerman, Robert Duvall',
    },
    {
        title: 'The Russians Are Coming, The Russians Are Coming',
        release: 1966,
        format: 'VHS',
        stars: 'Carl Reiner, Eva Marie Saint, Alan Arkin, Brian Keith',
    },
    {
        title: 'Jaws',
        release: 1975,
        format: 'DVD',
        stars: 'Roy Scheider, Robert Shaw, Richard Dreyfuss, Lorraine Gary',
    },
    {
        title: '2001: A Space Odyssey',
        release: 1968,
        format: 'DVD',
        stars: 'Keir Dullea, Gary Lockwood, William Sylvester, Douglas Rain',
    },
    {
        title: 'Harvey',
        release: 1950,
        format: 'DVD',
        stars: 'James Stewart, Josephine Hull, Peggy Dow, Charles Drake',
    },
    {
        title: 'Knocked Up',
        release: 2007,
        format: 'Blu-Ray',
        stars: 'Seth Rogen, Katherine Heigl, Paul Rudd, Leslie Mann',
    },
];

export const targetObject = {
    title: 'Harvey',
    release: 1950,
    format: 'DVD',
    stars: 'James Stewart, Josephine Hull, Peggy Dow, Charles Drake',
};
